#!/bin/bash
# =============================================================================
# setup.sh — Full EC2 Ubuntu Setup for SharkExchange Trading Bot
# =============================================================================
# Usage:
#   chmod +x setup.sh
#   sudo ./setup.sh
#
# What this does:
#   1. Updates system packages
#   2. Installs Docker + Docker Compose
#   3. Copies project files to /opt/tradingbot
#   4. Prompts for API keys and writes .env
#   5. Creates a systemd service (tradingbot.service) for auto-start on boot
#   6. Starts the bot
# =============================================================================

set -e  # Exit immediately on any error

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log()    { echo -e "${GREEN}[✔]${NC} $1"; }
warn()   { echo -e "${YELLOW}[!]${NC} $1"; }
error()  { echo -e "${RED}[✘]${NC} $1"; exit 1; }
header() { echo -e "\n${CYAN}══════════════════════════════════════${NC}"; echo -e "${CYAN}  $1${NC}"; echo -e "${CYAN}══════════════════════════════════════${NC}"; }

# ── Must run as root ──────────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  error "Please run as root: sudo ./setup.sh"
fi

# ── Detect actual user (the one who called sudo) ──────────────────────────────
ACTUAL_USER="${SUDO_USER:-$(whoami)}"
INSTALL_DIR="/opt/tradingbot"

header "Step 1: System Update"
apt-get update -y && apt-get upgrade -y
apt-get install -y curl git ca-certificates gnupg lsb-release
log "System updated."

# ── Step 2: Install Docker ────────────────────────────────────────────────────
header "Step 2: Install Docker"

if command -v docker &>/dev/null; then
  warn "Docker already installed: $(docker --version)"
else
  # Official Docker install (works on Ubuntu 20.04 / 22.04 / 24.04)
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null

  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  systemctl enable docker
  systemctl start docker

  # Add actual user to docker group so they don't need sudo for docker
  usermod -aG docker "$ACTUAL_USER"
  log "Docker installed: $(docker --version)"
fi

# ── Step 3: Install Docker Compose (standalone fallback) ──────────────────────
header "Step 3: Docker Compose"

if docker compose version &>/dev/null; then
  log "Docker Compose plugin available: $(docker compose version)"
elif command -v docker-compose &>/dev/null; then
  log "docker-compose already installed: $(docker-compose --version)"
else
  COMPOSE_VERSION="2.27.0"
  curl -SL "https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-linux-x86_64" \
    -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
  log "docker-compose installed: $(docker-compose --version)"
fi

# ── Step 4: Copy project to /opt/tradingbot ───────────────────────────────────
header "Step 4: Deploy Project Files"

# Determine source directory (where setup.sh lives)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/logs"

# Copy all project files (excluding .git and __pycache__)
rsync -av --exclude='.git' \
          --exclude='__pycache__' \
          --exclude='*.pyc' \
          --exclude='*.log' \
          "$SCRIPT_DIR/" "$INSTALL_DIR/"

# Fix ownership
chown -R "$ACTUAL_USER:$ACTUAL_USER" "$INSTALL_DIR"
log "Project copied to $INSTALL_DIR"

# ── Step 5: Configure .env ────────────────────────────────────────────────────
header "Step 5: API Key Configuration"

ENV_FILE="$INSTALL_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists at $ENV_FILE"
  read -rp "Overwrite existing .env? (y/N): " OVERWRITE_ENV
  if [[ "$OVERWRITE_ENV" =~ ^[Yy]$ ]]; then
    rm "$ENV_FILE"
  else
    log "Keeping existing .env"
  fi
fi

if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo -e "${YELLOW}Enter your SharkExchange API credentials:${NC}"
  echo -e "${YELLOW}(Leave blank to run in PAPER mode)${NC}"
  echo ""

  read -rp "  SHARK_API_KEY:    " SHARK_API_KEY
  read -rp "  SHARK_API_SECRET: " SHARK_API_SECRET

  cat > "$ENV_FILE" <<EOF
# SharkExchange.in API Credentials
# Generated by setup.sh on $(date)
SHARK_API_KEY=${SHARK_API_KEY}
SHARK_API_SECRET=${SHARK_API_SECRET}
EOF

  chmod 600 "$ENV_FILE"
  chown "$ACTUAL_USER:$ACTUAL_USER" "$ENV_FILE"
  log ".env written to $ENV_FILE"
fi

# ── Step 6: Create systemd service ────────────────────────────────────────────
header "Step 6: systemd Service (tradingbot)"

SERVICE_FILE="/etc/systemd/system/tradingbot.service"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=SharkExchange 5-Min BB Reversal Trading Bot
Documentation=https://github.com/your/repo
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${INSTALL_DIR}
User=${ACTUAL_USER}
Group=${ACTUAL_USER}

# Start the bot via Docker Compose
ExecStart=/usr/bin/docker compose -f ${INSTALL_DIR}/docker-compose.yml up -d --build

# Stop: graceful shutdown
ExecStop=/usr/bin/docker compose -f ${INSTALL_DIR}/docker-compose.yml down

# Restart policy (handled by docker compose restart: unless-stopped)
Restart=on-failure
RestartSec=10

StandardOutput=journal
StandardError=journal
SyslogIdentifier=tradingbot

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable tradingbot.service
log "systemd service created and enabled: tradingbot.service"

# ── Step 7: Open firewall port 5000 ──────────────────────────────────────────
header "Step 7: Firewall (UFW)"

if command -v ufw &>/dev/null; then
  ufw allow 22/tcp comment "SSH"      2>/dev/null || true
  ufw allow 5000/tcp comment "TradingBot Dashboard" 2>/dev/null || true
  log "UFW: port 5000 opened for dashboard"
else
  warn "UFW not found — make sure port 5000 is open in your EC2 Security Group"
fi

# ── Step 8: Build image & Start ───────────────────────────────────────────────
header "Step 8: Build Docker Image & Start Bot"

cd "$INSTALL_DIR"

# Build without cache to ensure fresh image
docker compose build --no-cache
docker compose up -d

log "Bot is starting..."

# Wait a moment then show status
sleep 5
docker compose ps

# ── Step 9: Enable systemd service ───────────────────────────────────────────
systemctl start tradingbot.service 2>/dev/null || true

# ── Done ──────────────────────────────────────────────────────────────────────
header "✅ Setup Complete!"

EC2_IP=$(curl -s --max-time 5 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "<your-ec2-ip>")

echo ""
echo -e "  ${GREEN}Dashboard URL :${NC}  http://${EC2_IP}:5000"
echo -e "  ${GREEN}Install dir   :${NC}  ${INSTALL_DIR}"
echo -e "  ${GREEN}Logs          :${NC}  ${INSTALL_DIR}/logs/ and ${INSTALL_DIR}/trading_bot.log"
echo ""
echo -e "  ${CYAN}Useful commands:${NC}"
echo -e "    View live logs   →  docker compose -C ${INSTALL_DIR} logs -f"
echo -e "    Stop bot         →  sudo systemctl stop tradingbot"
echo -e "    Start bot        →  sudo systemctl start tradingbot"
echo -e "    Restart bot      →  sudo systemctl restart tradingbot"
echo -e "    Service status   →  sudo systemctl status tradingbot"
echo -e "    Container status →  docker ps"
echo ""
echo -e "  ${YELLOW}⚠  Remember: open port 5000 in your EC2 Security Group!${NC}"
echo ""
